[tool.ruff]
line-length = 99
src = ["project/**/*.py", "huntsite/**/*.py"]
extend-exclude = [
    "manage.py",
    "project/asgi.py",
    "project/wsgi.py",
    "**/migrations/**/*",
    "**/apps.py",
]

[tool.ruff.lint]
select = [
    "E", # Pyflakes
    "F", # Pycodestyle
    "I", # isort
]
unfixable = ["F"]

[tool.ruff.lint.isort]
known-first-party = ["huntsite"]
force-sort-within-sections = true

[tool.djlint]
profile = "django"
indent = 2
extend_exclude = "templates/allauth"
