services:
  - name: advent-hunt-web
    buildCommand: "./scripts/build.sh"
    runtime: python
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: advent-hunt-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    plan: free
    region: ohio
    startCommand: "./scripts/deploy.sh"
    type: web

databases:
  - name: advent-hunt-db
    databaseName: project_db
    ipAllowList: []
    plan: free
    region: ohio
    user: project_db_user
