# Generated by Django 5.0.4 on 2024-11-30 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_alter_flair_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerDashboardPermission',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organizer_dashboard_permission', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organizer Dashboard Permission',
                'verbose_name_plural': 'Organizer Dashboard Permissions',
            },
        ),
    ]
