# Generated by Django 5.0.4 on 2024-08-27 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventcalendarentry',
            name='id',
        ),
        migrations.AlterField(
            model_name='adventcalendarentry',
            name='puzzle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='calendar_entry', serialize=False, to='puzzles.puzzle'),
        ),
    ]
