# Generated by Django 5.0.4 on 2024-08-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_remove_adventcalendarentry_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='name',
            new_name='title',
        ),
    ]
