# Generated by Django 5.0.4 on 2024-08-31 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_rename_name_puzzle_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipboardData',
            fields=[
                ('puzzle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clipboard_data', serialize=False, to='puzzles.puzzle')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Clipboard Data',
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.CharField(default='<i class="bi bi-box-arrow-up-right"></i>', help_text='HTML displayed for the link (child of <a> tag).', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('order_by', models.IntegerField(default=0)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='puzzles.puzzle')),
            ],
            options={
                'verbose_name_plural': 'External Links',
            },
        ),
    ]
