# Generated by Django 5.0.4 on 2024-07-22 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_alter_guess_evaluation_alter_guess_puzzle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
