# Generated by Django 5.0.4 on 2024-07-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_puzzle_available_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventcalendarentry',
            options={'verbose_name_plural': 'Advent Calendar Entries'},
        ),
    ]
