# Generated by Django 5.0.4 on 2024-11-18 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_puzzleattributionsentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='canned_hints_available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CannedHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order_by', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_hints', to='puzzles.puzzle')),
            ],
        ),
    ]
