# Generated by Django 5.0.4 on 2024-12-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_puzzle_canned_hints_available_at_cannedhint'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='solution_pdf_url',
            field=models.URLField(blank=True),
        ),
    ]
