# Generated by Django 5.0.4 on 2024-07-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_alter_adventcalendarentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzle',
            options={'default_manager_name': 'objects'},
        ),
    ]
