# Generated by Django 5.0.4 on 2024-08-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0009_finish_metapuzzleinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metapuzzleinfo',
            options={'verbose_name_plural': 'Metapuzzle Info'},
        ),
    ]
