# Generated by Django 5.0.4 on 2024-08-25 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0011_erratum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erratum',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errata', to='puzzles.puzzle'),
        ),
    ]
