# Generated by Django 5.0.4 on 2024-08-03 23:03

from django.db import migrations
from django.conf import settings

def set_site_domain(apps, schema_editor):
    """Set site domain from settings."""
    Site = apps.get_model("sites", "Site")
    site = Site.objects.get(pk=settings.SITE_ID)
    site.domain = settings.SITE_DOMAIN
    site.save()

class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(set_site_domain),
    ]
