# Generated by Django 5.0.4 on 2024-07-21 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puzzles', '0003_alter_guess_options_adventcalendarentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order_by', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Entries',
            },
        ),
        migrations.CreateModel(
            name='StoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order_by', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puzzle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzles.puzzle')),
            ],
            options={
                'verbose_name_plural': 'Story Entries',
            },
        ),
    ]
