# Generated by Django 5.0.4 on 2024-08-25 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyentry',
            name='puzzle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle'),
        ),
    ]
