# Generated by Django 5.0.4 on 2024-08-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_storyentry_is_final'),
        ('puzzles', '0009_finish_metapuzzleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyentry',
            name='puzzle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle'),
        ),
    ]
