# Generated by Django 5.0.4 on 2025-01-06 20:05

import huntsite.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_updateentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrapupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('available_at', models.DateTimeField(default=huntsite.content.models._wrapup_entry_available_at_default)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
