# Generated by Django 5.0.4 on 2024-07-20 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='members',
            field=models.CharField(blank=True, help_text='List of team members.', max_length=255),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
