# Generated by Django 5.0.4 on 2024-10-20 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_flair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flair',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='flairs', to=settings.AUTH_USER_MODEL),
        ),
    ]
