# Generated by Django 5.0.4 on 2024-08-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_user_is_tester'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
