# Generated by Django 5.0.4 on 2024-08-02 05:52

import huntsite.teams.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', huntsite.teams.models.UserManager()),
            ],
        ),
    ]
