# Generated by Django 5.0.4 on 2024-08-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_user_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='members',
            field=models.CharField(blank=True, help_text='Who is on your team? Will be publicly shown on your team profile.', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_name',
            field=models.CharField(help_text='How the team will be publicly displayed.', max_length=127, unique=True),
        ),
    ]
